### ISSUE TITLE
Confusion about pretrained-model

### ISSUE THREAD

**Issue by laisimiao** [bfshi/TOAST#3]
Hi, I have a question about pretrain model in model zoo [here](https://github.com/bfshi/TOAST/tree/main/visual_classification#model-zoo). They are pretrained after pre-tuning or pretrained after FGVC?

**Comment by bfshi** [comment]
Hi, they are pretrained after pre-tuning. Actually we didn’t pre-tune the `top_down_transform` (i.e., we keep it as an identity matrix during pre-tuning). When you load the pre-tuned weights, you can use `strict=false` in `load_state_dict`

**Comment by laisimiao** [comment]
Ok, thank you for your response!
